package app.purecipes.shared.domain.model

private val catalogueGroups: List<IngredientCatalogueGroup> = listOf(
	IngredientCatalogueGroup(
		name = "Poultry & Eggs",
		items = listOf(
			"Chicken",
			"Chicken Thighs",
			"Duck",
			"Eggs",
			"Turkey",
			"Turkey Mince",
		),
	),
	IngredientCatalogueGroup(
		name = "Meats",
		items = listOf(
			"Bacon",
			"Beef",
			"Beef Mince",
			"Chorizo",
			"Ham",
			"Lamb",
			"Pancetta",
			"Pork",
			"Sausage",
			"Steak",
		),
	),
	IngredientCatalogueGroup(
		name = "Vegetables",
		items = listOf(
			"Anaheim Pepper",
			"Artichoke",
			"Asparagus",
			"Aubergine",
			"Beansprouts",
			"Beetroot",
			"Broccoli",
			"Brussels Sprout",
			"Butternut Squash",
			"Cabbage",
			"Carrot",
			"Cauliflower",
			"Celeriac",
			"Celery",
			"Cherry Tomatoes",
			"Collard Greens",
			"Cucumber",
			"Endive",
			"Fennel",
			"Garlic",
			"Green Onion",
			"Jalapeno",
			"Kale",
			"Leek",
			"Lettuce",
			"Okra",
			"Onion",
			"Pak Choi",
			"Parsnip",
			"Pepper",
			"Potato",
			"Pumpkin",
			"Radicchio",
			"Radish",
			"Red Onion",
			"Rocket",
			"Romaine Lettuce",
			"Shallot",
			"Spinach",
			"Spring Greens",
			"Squash",
			"Sweet Potato",
			"Sweetcorn",
			"Swiss Chard",
			"Tomatillo",
			"Tomatillos",
			"Tomato",
			"Turnip",
			"White Onion",
			"Yellow Onion",
			"Zucchini",
		),
	),
	IngredientCatalogueGroup(
		name = "Fish",
		items = listOf(
			"Anchovy",
			"Cod",
			"Fish",
			"Haddock",
			"Mackerel",
			"Salmon",
			"Sardines",
			"Tilapia",
			"Tuna",
		),
	),
	IngredientCatalogueGroup(
		name = "Seafood",
		items = listOf(
			"Clams",
			"Crab",
			"Mussels",
			"Prawns",
			"Scallops",
			"Shrimp",
		),
	),
	IngredientCatalogueGroup(
		name = "Mushrooms",
		items = listOf(
			"Mushroom",
			"Oyster Mushroom",
			"Porcini",
			"Portobello",
			"Shiitake",
		),
	),
	IngredientCatalogueGroup(
		name = "Legumes",
		items = listOf(
			"Beans",
			"Chickpeas",
			"Green Beans",
			"Lentils",
			"Peas",
		),
	),
	IngredientCatalogueGroup(
		name = "Fruits",
		items = listOf(
			"Apple",
			"Apricot",
			"Avocado",
			"Banana",
			"Date",
			"Fig",
			"Grapes",
			"Lemon",
			"Lime",
			"Mango",
			"Orange",
			"Peach",
			"Pear",
			"Pineapple",
			"Plantain",
			"Pomegranate",
			"Raisin",
			"Sultanas",
		),
	),
	IngredientCatalogueGroup(
		name = "Berries",
		items = listOf(
			"Blackberry",
			"Blueberry",
			"Cherry",
			"Cranberries",
			"Raspberry",
			"Strawberry",
		),
	),
	IngredientCatalogueGroup(
		name = "Dairy",
		items = listOf(
			"Butter",
			"Buttermilk",
			"Cottage Cheese",
			"Cream",
			"Cream Cheese",
			"Crème Fraîche",
			"Double Cream",
			"Ghee",
			"Greek Yoghurt",
			"Mascarpone",
			"Milk",
			"Ricotta",
			"Single Cream",
			"Sour Cream",
			"Yoghurt",
		),
	),
	IngredientCatalogueGroup(
		name = "Cheeses",
		items = listOf(
			"Cheddar",
			"Cheese",
			"Feta",
			"Goat Cheese",
			"Gruyere",
			"Halloumi",
			"Monterey Jack",
			"Mozzarella",
			"Paneer",
			"Parmesan",
			"Pecorino Romano",
			"Sharp Cheddar",
		),
	),
	IngredientCatalogueGroup(
		name = "Grains & Cereals",
		items = listOf(
			"Cornmeal",
			"Couscous",
			"Oats",
			"Polenta",
			"Quinoa",
			"Rice",
			"Semolina",
		),
	),
	IngredientCatalogueGroup(
		name = "Herbs & Spices",
		items = listOf(
			"Allspice",
			"Basil",
			"Bay Leaf",
			"Black Pepper",
			"Cajun Seasoning",
			"Cardamom",
			"Chili",
			"Chilli Flakes",
			"Chinese Five-Spice",
			"Chive",
			"Cilantro",
			"Cinnamon",
			"Clove",
			"Cloves",
			"Cumin",
			"Curry Powder",
			"Dill",
			"Fennel Seed",
			"Garam Masala",
			"Ginger",
			"Lemongrass",
			"Mint",
			"Nigella Seed",
			"Nutmeg",
			"Old Bay Seasoning",
			"Oregano",
			"Paprika",
			"Parsley",
			"Rosemary",
			"Sage",
			"Shawarma Spice",
			"Sichuan Peppercorns",
			"Star Anise",
			"Sumac",
			"Tagine Spice",
			"Tarragon",
			"Thyme",
			"Turmeric",
			"White Pepper",
			"Za'atar",
		),
	),
	IngredientCatalogueGroup(
		name = "Pasta",
		items = listOf(
			"Fettuccine",
			"Fusilli",
			"Lasagna Sheets",
			"Linguine",
			"Noodles",
			"Orzo",
			"Pasta",
			"Penne",
			"Ramen",
			"Rigatoni",
			"Spaghetti",
			"Tagliatelle",
			"Udon",
		),
	),
	IngredientCatalogueGroup(
		name = "Oils & Fats",
		items = listOf(
			"Canola Oil",
			"Coconut Oil",
			"Grapeseed Oil",
			"Groundnut Oil",
			"Olive Oil",
			"Sesame Oil",
			"Sunflower Oil",
		),
	),
	IngredientCatalogueGroup(
		name = "Bread & Salty Snacks",
		items = listOf(
			"Bread",
			"Breadcrumbs",
			"Brioche Buns",
			"Ciabatta",
			"Hash Browns",
			"Hot Dog Buns",
			"Panko",
		),
	),
	IngredientCatalogueGroup(
		name = "Baking",
		items = listOf(
			"Baking Powder",
			"Baking Soda",
			"Cornflour",
			"Flour",
			"Sourdough Starter",
			"Vanilla",
		),
	),
	IngredientCatalogueGroup(
		name = "Condiments",
		items = listOf(
			"BBQ Sauce",
			"Cranberry Sauce",
			"Harissa",
			"Hoisin Sauce",
			"Hot Sauce",
			"Ketchup",
			"Mango Chutney",
			"Marinara Sauce",
			"Mayonnaise",
			"Miso Paste",
			"Mustard",
			"Olive Brine",
			"Oyster Sauce",
			"Peri Peri Seasoning",
			"Soy Sauce",
			"Sriracha",
			"Tahini",
			"Teriyaki Sauce",
			"Worcestershire Sauce",
		),
	),
	IngredientCatalogueGroup(
		name = "Wine, Beer & Spirits",
		items = listOf(
			"Beer",
			"Brandy",
			"Marsala Wine",
			"Mirin",
			"Red Wine",
			"Rum",
			"Shaoxing Wine",
			"Vodka",
			"White Wine",
		),
	),
	IngredientCatalogueGroup(
		name = "Canned Food",
		items = listOf(
			"Capers",
			"Coconut Milk",
			"Diced Tomatoes",
			"Passata",
			"Tomato Paste",
		),
	),
	IngredientCatalogueGroup(
		name = "Beverages",
		items = listOf(
			"Apple Juice",
			"Coffee",
			"Lemonade",
			"Orange Juice",
			"Tea",
		),
	),
	IngredientCatalogueGroup(
		name = "Dressings & Vinegars",
		items = listOf(
			"Apple Cider Vinegar",
			"Guacamole",
			"Pico de Gallo",
			"Red Wine Vinegar",
			"Salsa",
			"Salsa Verde",
			"Tzatziki",
			"Vinegar",
			"White Wine Vinegar",
		),
	),
	IngredientCatalogueGroup(
		name = "Nuts & Seeds",
		items = listOf(
			"Almonds",
			"Brazil Nuts",
			"Cashews",
			"Chestnuts",
			"Hazelnuts",
			"Macadamia Nuts",
			"Peanuts",
			"Pecans",
			"Pine Nuts",
			"Pistachios",
			"Sesame",
			"Walnuts",
		),
	),
	IngredientCatalogueGroup(
		name = "Supplements & Extracts",
		items = listOf(
			"Almond Extract",
			"Lemon Extract",
			"Nutritional Yeast",
			"Peppermint Extract",
			"Vanilla Extract",
		),
	),
	IngredientCatalogueGroup(
		name = "Soups, Stews & Stocks",
		items = listOf(
			"Beef Stock",
			"Bone Broth",
			"Chicken Stock",
			"Fish Stock",
			"Vegetable Stock",
		),
	),
	IngredientCatalogueGroup(
		name = "Sugar & Sweeteners",
		items = listOf(
			"Brown Sugar",
			"Golden Syrup",
			"Honey",
			"Maple Syrup",
			"Sugar",
		),
	),
	IngredientCatalogueGroup(
		name = "Dessert & Sweets",
		items = listOf(
			"Caramel",
			"Chocolate",
			"Cocoa Powder",
			"Icing Sugar",
			"Marshmallows",
		),
	),
	IngredientCatalogueGroup(
		name = "Dairy-Free and Meat Substitutes",
		items = listOf(
			"Jackfruit",
			"Plant-Based Mince",
			"Seitan",
			"Tempeh",
			"Tofu",
		),
	),
	IngredientCatalogueGroup(
		name = "Pre-Made Doughs & Wrappers",
		items = listOf(
			"Filo Pastry",
			"Pizza Dough",
			"Puff Pastry",
			"Shortcrust Pastry",
			"Spring Roll Wrappers",
			"Tortilla",
		),
	),
)

object IngredientCatalogue {
	val groups: List<IngredientCatalogueGroup> = catalogueGroups

	val allItems: Set<String> = groups.flatMap { it.items }.toSet()
}
