package app.purecipes.backend.feature.nutrition

internal object NutritionSeedOverrides {
	val preferredDescriptionByCatalogueName: Map<String, String> = mapOf(
		"Flour" to "Flour, wheat, all-purpose, enriched, unbleached",
		"Eggs" to "Eggs, Grade A, Large, egg whole",
		"Milk" to "Milk, whole, 3.25% milkfat, with added vitamin D",
		"Butter" to "Butter, stick, unsalted",
		"Olive Oil" to "Oil, olive, extra virgin",
		"Onion" to "Onions, yellow, raw",
		"Yellow Onion" to "Onions, yellow, raw",
		"White Onion" to "Onions, white, raw",
		"Red Onion" to "Onions, red, raw",
		"Garlic" to "Garlic, raw",
		"Chicken" to "Chicken, breast, boneless, skinless, raw",
		"Chicken Thighs" to "Chicken, thigh, boneless, skinless, raw",
		"Turkey" to "Turkey, ground, 93% lean/ 7% fat, raw",
		"Sugar" to "Sugars, granulated",
		"Brown Sugar" to "Sugars, granulated",
		"Icing Sugar" to "Sugars, granulated",
		"Rice" to "Rice, white, long grain, unenriched, raw",
		"Tomato" to "Tomatoes, grape, raw",
		"Cherry Tomatoes" to "Tomatoes, grape, raw",
		"Potato" to "Potatoes, gold, without skin, raw",
		"Sweet Potato" to "Sweet potatoes, orange flesh, without skin, raw",
		"Carrot" to "Carrots, mature, raw",
		"Broccoli" to "Broccoli, raw",
		"Spinach" to "Spinach, baby",
		"Salmon" to "Fish, salmon, Atlantic, farm raised, raw",
		"Tuna" to "Fish, tuna, light, canned in water, drained solids",
		"Bacon" to "Pork, cured, bacon, cooked, baked",
		"Beef Mince" to "Beef, ground, 90% lean meat / 10% fat, raw",
		"Beef" to "Beef, chuck, roast, boneless, choice, raw",
		"Pork" to "Pork, loin, tenderloin, boneless, raw",
		"Cheddar" to "Cheese, cheddar",
		"Parmesan" to "Cheese, parmesan, grated",
		"Mozzarella" to "Cheese, mozzarella, low moisture, part-skim",
		"Yoghurt" to "Yogurt, plain, whole milk",
		"Greek Yoghurt" to "Yogurt, Greek, plain, whole milk",
		"Cream" to "Cream, heavy",
		"Oats" to "Oats, whole grain, rolled, old fashioned",
		"Bread" to "Bread, white, commercially prepared",
		"Pasta" to "Pasta, dry, unenriched",
		"Spaghetti" to "Pasta, dry, unenriched",
		"Penne" to "Pasta, dry, unenriched",
		"Fusilli" to "Pasta, dry, unenriched",
		"Noodles" to "Noodles, egg, dry, enriched",
		"Honey" to "Honey",
		"Vegetable Stock" to "Soup, vegetable broth, ready to serve",
		"Chicken Stock" to "Soup, chicken broth, ready-to-serve",
		"Beef Stock" to "Soup, beef broth, less/reduced sodium, ready to serve",
	)
}
