package app.purecipes.backend.feature.nutrition

import java.text.Normalizer

internal object NutritionNameNormalizer {

	private val NON_ALPHANUMERIC = Regex("[^a-z0-9]+")

	private val SUCH_AS_CLAUSE = Regex(""",?\s*such as\b.*""", RegexOption.IGNORE_CASE)

	private val COMBINING_MARKS = Regex("\\p{M}+")

	private val preparationTokens = setOf(
		"batons",
		"beaten",
		"bias",
		"bite",
		"blanched",
		"boned",
		"broken",
		"butterflied",
		"charred",
		"chilled",
		"chiffonade",
		"chopped",
		"chunks",
		"coarsely",
		"cold",
		"concentrated",
		"cooled",
		"cored",
		"crispy",
		"crosswise",
		"crushed",
		"cubed",
		"cubes",
		"cut",
		"defrosted",
		"deseeded",
		"deveined",
		"diagonal",
		"diagonally",
		"dice",
		"diced",
		"divided",
		"drained",
		"dried",
		"fine",
		"finely",
		"florets",
		"fresh",
		"freshly",
		"grated",
		"ground",
		"halved",
		"halves",
		"hearts",
		"homemade",
		"hulled",
		"inch",
		"inches",
		"juiced",
		"julienned",
		"knob",
		"knobs",
		"large",
		"leaves",
		"lengthwise",
		"lightly",
		"mashed",
		"medium",
		"melted",
		"minced",
		"moons",
		"needed",
		"note",
		"notes",
		"peeled",
		"picked",
		"pitted",
		"pounded",
		"preferably",
		"quartered",
		"removed",
		"rinsed",
		"room",
		"roughly",
		"rounds",
		"scrubbed",
		"see",
		"seeded",
		"separated",
		"shaken",
		"shredded",
		"shucked",
		"sifted",
		"sized",
		"skinned",
		"sliced",
		"slices",
		"slightly",
		"small",
		"smashed",
		"smoked",
		"snipped",
		"soaked",
		"softened",
		"spooned",
		"squeezed",
		"stemmed",
		"stems",
		"stirred",
		"strips",
		"temperature",
		"tenderized",
		"thawed",
		"thick",
		"thinly",
		"toasted",
		"torn",
		"trimmed",
		"undrained",
		"unpeeled",
		"warmed",
		"washed",
		"wedges",
		"whisked",
		"zested",
	)

	private val measureLeftoverTokens = setOf(
		"about",
		"and",
		"approx",
		"approximately",
		"cup",
		"cups",
		"each",
		"fluid",
		"gram",
		"grams",
		"kilo",
		"kilogram",
		"kilograms",
		"liter",
		"liters",
		"litre",
		"litres",
		"milliliter",
		"milliliters",
		"millilitre",
		"millilitres",
		"only",
		"or",
		"ounce",
		"ounces",
		"plus",
		"pound",
		"pounds",
		"sprigs",
		"tablespoon",
		"tablespoons",
		"tbsp",
		"tbsps",
		"teaspoon",
		"teaspoons",
		"tender",
		"total",
		"tsp",
		"tsps",
		"weight",
		"with",
	)

	private val fillerTokens = setOf(
		"above",
		"according",
		"additional",
		"against",
		"bottoms",
		"bought",
		"brushing",
		"clear",
		"cook",
		"couple",
		"crusts",
		"cutting",
		"deep",
		"depending",
		"desired",
		"diameter",
		"directions",
		"discarded",
		"dredging",
		"drizzling",
		"dusting",
		"ends",
		"english",
		"excess",
		"eyeball",
		"for",
		"fork",
		"from",
		"frying",
		"garnish",
		"garnishing",
		"granules",
		"grater",
		"greasing",
		"griddling",
		"hand",
		"holes",
		"hours",
		"husk",
		"husked",
		"instructions",
		"into",
		"larger",
		"least",
		"left",
		"lengths",
		"liberal",
		"loosely",
		"minutes",
		"more",
		"mortar",
		"oiling",
		"optional",
		"packed",
		"palm",
		"palmfuls",
		"pan",
		"parts",
		"pestle",
		"piece",
		"pieces",
		"poked",
		"preference",
		"prepared",
		"pure",
		"reserved",
		"rolling",
		"runs",
		"sauteing",
		"serve",
		"serving",
		"size",
		"soften",
		"some",
		"sprinkling",
		"stick",
		"sticks",
		"store",
		"surface",
		"taste",
		"than",
		"the",
		"then",
		"thickness",
		"through",
		"tops",
		"tough",
		"turn",
		"turns",
		"until",
		"using",
		"way",
		"well",
		"without",
	)

	private val brandTokens = setOf(
		"aldi",
		"asda",
		"coop",
		"cooperative",
		"fairtrade",
		"lidl",
		"marks",
		"morrison",
		"morrisons",
		"operative",
		"sainsbury",
		"sainsburys",
		"spencer",
		"tesco",
		"waitrose",
	)

	private val packagingTokens = setOf(
		"bag",
		"bags",
		"bottle",
		"bottles",
		"box",
		"boxes",
		"can",
		"cans",
		"carton",
		"container",
		"containers",
		"envelope",
		"jar",
		"jars",
		"pack",
		"package",
		"packages",
		"packet",
		"packets",
		"pot",
		"tin",
		"tins",
	)

	private val sizeOnlyTokens = setOf(
		"extra",
		"extra-large",
		"jumbo",
		"large",
		"medium",
		"small",
	)

	fun normalize(value: String): String {
		val ascii = COMBINING_MARKS.replace(
			Normalizer.normalize(value.lowercase(), Normalizer.Form.NFKD),
			"",
		)
		return NON_ALPHANUMERIC.replace(ascii, " ").trim()
	}

	fun tokens(normalized: String): List<String> =
		normalized.split(' ').filter { token -> token.length >= MIN_TOKEN_LENGTH }

	fun forLookup(value: String): String {
		val withoutClause = SUCH_AS_CLAUSE.replace(value.substringBefore(';').trim(), "").trim()
		val normalized = normalize(withoutClause)
		return tokens(normalized).filterNot { token ->
			token.all(Char::isDigit) ||
				token in preparationTokens ||
				token in measureLeftoverTokens ||
				token in fillerTokens ||
				token in brandTokens ||
				token in packagingTokens
		}.joinToString(" ")
	}

	fun hasMeaningfulFoodName(value: String): Boolean {
		val lookup = forLookup(value)
		if (lookup.isNotBlank()) {
			return true
		}
		val normalizedTokens = tokens(normalize(value)).filterNot { token -> token.all(Char::isDigit) }
		return normalizedTokens.any { token -> token !in sizeOnlyTokens && token !in preparationTokens }
	}

	private const val MIN_TOKEN_LENGTH = 3
}
