[versions]

#common configuration

versionCode = "7"
versionName = "0.4.0"
minSdkVersion = "24"
compileSdkVersion = "37"
targetSdkVersion = "37"

#platform

androidGradlePlugin = "9.2.1"
appDistributionPlugin = "5.3.0"
#androidGradlePlugin = "7.3.1" # For IntelliJ plugin runIde
coroutines = "1.11.0"
crashkios = "0.9.0"
crashlyticsPlugin = "3.0.7"
jdk = "21"
kotlin = "2.4.0"
kotlinx-collections = "0.5.0"
kotlinx-datetime = "0.8.0-0.6.x-compat"
kotlinx-serialization = "1.11.0"
ksp = "2.3.9"

#other

androidx-activity = "1.13.0"
#androidx-appcompat = "1.7.1"
androidx-composeBom = "2026.06.00"
androidx-composeMaterial3 = "1.5.0-alpha22" #For alpha releases only
androidx-composeUiAndroidTest = "1.11.3"
androidx-lifecycle = "2.11.0"
#androidx-navigation = "2.9.1"
#androidx-paletteKtx = "1.0.0"
#androidx-room = "2.7.2"
androidx-testCore = "1.7.0"
androidx-testExtJUnit = "1.3.0"
#androidx-testRules = "1.6.1"
androidx-testRunner = "1.7.0"
androidx-testEspresso = "3.7.0"
#androidx-work = "2.10.2"
#autoBind = "2.0.0"
babestudios-base = "3.2.1"
buildKonfig = "0.21.2"
#compose-screenshotTesting = "0.0.1-alpha09"
#chucker = "4.2.0"
coil = "3.5.0"
googleServices = "4.5.0"
#decompose = "3.5.0"
dejavu = "0.3.1"
dependencyAnalysis = "3.10.0"
detekt = "1.23.8"
detekt-compose = "0.4.28"
diamondedge-logging = "2.1.1"
essenty = "2.5.0"
h2 = "2.4.240"
#facebook = "16.1.2"
firebaseBom = "34.15.0"
gradleDoctor = "0.12.1"
#graphql = "4.3.1"
#javaPoet = "1.13.0"
hikariCp = "7.1.0"
jetbrains-androidXLifecycle = "2.10.0"
jetBrains-compose = "1.11.1"
jetbrains-composeMaterial3 = "1.11.0-alpha07"
jetbrains-navigation3 = "1.1.1"
jUnit = "4.13.2"
jUnit5 = "6.1.0"
kmpauth = "2.5.0-alpha01"
kmpnotifier = "2.0.0"
kotest = "6.2.1"
kotlinResult = "2.3.1"
kotlinRetry = "2.0.2"
ktor = "3.5.0"
ktorfit = "2.7.5"
metro = "1.2.1"
mixpanelAndroid = "8.8.0"
#mockk = "1.13.8" #1.13.4 issue: https://github.com/mockk/mockk/issues/1035
mokkery = "3.4.1"
multiplatform-settings = "1.3.0"
okhttp = "5.4.0"
#parcelize-darwin = "0.2.4"
postgresql = "42.7.11"
#retrofit = "2.11.0"
#robolectric = "4.15.1"
shadow = "9.4.2"
#skie = "0.10.4"
testcontainers = "2.0.5"
tensorflow-java = "1.1.0"
uri-kmp = "0.0.21"
usercentrics = "2.27.1"

[libraries]

agp = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }

androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-annotation = "androidx.annotation:annotation:1.10.0"
#androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
#androidx-appCompatResources = { group = "androidx.appcompat", name = "appcompat-resources", version.ref = "androidx-appcompat" }
#androidx-browser = "androidx.browser:browser:1.8.0"
#androidx-cardView = "androidx.cardview:cardview:1.0.0"
#androidx-collection = "androidx.collection:collection:1.5.0"

androidx-composeBom = { module = "androidx.compose:compose-bom", version.ref = "androidx-composeBom" }

#androidx-composeAnimation = { module = "androidx.compose.animation:animation" }
androidx-composeAnimationCore = { module = "androidx.compose.animation:animation-core" }
androidx-composeFoundation = { module = "androidx.compose.foundation:foundation" }
androidx-composeFoundationLayout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-composeFoundationLayoutAndroid = { module = "androidx.compose.foundation:foundation-layout-android" }
androidx-composeRuntime = { module = "androidx.compose.runtime:runtime" }
androidx-composeRuntimeSaveable = { module = "androidx.compose.runtime:runtime-saveable" }
androidx-composeMaterialIconsCore = { module = "androidx.compose.material:material-icons-core" }
androidx-composeMaterialIconsExtended = { module = "androidx.compose.material:material-icons-extended" }

androidx-composeUi = { group = "androidx.compose.ui", name = "ui" }
androidx-composeUiGraphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-composeUiText = { group = "androidx.compose.ui", name = "ui-text" }
androidx-composeUiTest = { group = "androidx.compose.ui", name = "ui-test" }
androidx-composeUiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-composeUiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" } #For adding Activities
androidx-composeUiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-composeUiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-composeUiUnit = { group = "androidx.compose.ui", name = "ui-unit" }

#Not in BOM as of 2023.10.01 !!!
androidx-composeUiTestJunit4Android = { group = "androidx.compose.ui", name = "ui-test-junit4-android", version.ref = "androidx-composeUiAndroidTest" }
androidx-composeUiTestManifestAndroid = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "androidx-composeUiAndroidTest" }

#In BOM, but alpha is often needed
androidx-composeMaterial3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-composeMaterial3" }
#androidx-composeMaterial3 = { module = "androidx.compose.material3:material3" }

#androidx-constraintLayout = "androidx.constraintlayout:constraintlayout:2.2.1"
androidx-constraintLayoutCompose = "androidx.constraintlayout:constraintlayout-compose:1.1.1"

androidx-core = "androidx.core:core:1.19.0" #Bundle
#androidx-coreKtx = "androidx.core:core-ktx:1.16.0" #Bundle

#androidx-datastore = "androidx.datastore:datastore-preferences:1.1.7"

androidx-lifecycleCommon = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-lifecycleRuntime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidx-lifecycle" }
#androidx-lifecycleRuntimeCompose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref ="androidx-lifecycle" }
#androidx-lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
#androidx-lifecycleProcess = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-lifecycleViewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
#androidx-lifecycleViewmodelSavedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
#androidx-lifecycleViewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }

#androidx-media = "androidx.media:media:1.7.0"
#androidx-mediaRouter = "androidx.mediarouter:mediarouter:1.8.1"

#androidx-paletteKtx = { group = "androidx.palette", name = "palette-ktx", version.ref = "androidx-paletteKtx" }
#androidx-preferenceKtx = "androidx.preference:preference-ktx:1.2.1"
#androidx-recyclerView = "androidx.recyclerview:recyclerview:1.4.0"

#androidx-roomCommon = { module = "androidx.room:room-common", version.ref = "androidx-room" }
#androidx-roomCompiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
#androidx-roomKtx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
#androidx-roomRuntime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
#androidx-roomTesting = { module = "androidx.room:room-testing", version.ref = "androidx-room" }

androidx-savedState = "androidx.savedstate:savedstate:1.5.0"
androidx-splash = "androidx.core:core-splashscreen:1.2.0"
#androidx-sqlite = "androidx.sqlite:sqlite:2.5.2"
#androidx-startup = "androidx.startup:startup-runtime:1.2.0"
#androidx-swipeRefreshLayout = "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
#androidx-viewPager2 = "androidx.viewpager2:viewpager2:1.1.0"

#androidx-window = "androidx.window:window:1.4.0"
#androidx-workmanagerKtx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
#androidx-workmanagerTesting = { module = "androidx.work:work-testing", version.ref = "androidx-work" }

androidx-testCore = { group = "androidx.test", name = "core", version.ref = "androidx-testCore" }
#androidx-testCoreKtx = { module = "androidx.test:core-ktx", version.ref = "androidx-testCore" }
androidx-testEspresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-testEspresso" }
#androidx-testEspressoContrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidx-testEspresso" }
#androidx-testEspressoIntents = { module = "androidx.test.espresso:espresso-intents", version.ref = "androidx-testEspresso" }
androidx-testExtJUnit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExtJUnit" }
#androidx-testExtJUnitKtx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-testExtJUnit" }
#androidx-testRules = { module = "androidx.test:rules", version.ref = "androidx-testRules" }
androidx-testRunner = { module = "androidx.test:runner", version.ref = "androidx-testRunner" }
androidx-vectordrawableAnimated = "androidx.vectordrawable:vectordrawable-animated:1.2.0"
#androidx-testOrchestrator = "androidx.test:orchestrator:1.5.1"
#androidx-testUiAutomator = "androidx.test.uiautomator:uiautomator:2.3.0"

assertj = "org.assertj:assertj-core:3.27.7"

baBeStudios-baseKotlin = { module = "io.bitbucket.babestudios:base-kotlin", version.ref = "babestudios-base" }
baBeStudios-baseData = { module = "io.bitbucket.babestudios:base-data", version.ref = "babestudios-base" }
baBeStudios-baseAndroid = { module = "io.bitbucket.babestudios:base-android", version.ref = "babestudios-base" }
baBeStudios-baseCompose = { module = "io.bitbucket.babestudios:base-compose", version.ref = "babestudios-base" }

coil-core = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil" }
coil-networkKtor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

crashkios-crashlytics = { module = "co.touchlab.crashkios:crashlytics", version.ref = "crashkios" }

#decompose-core = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
#decompose-extensions = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
dejavu = { module = "me.mmckenna.dejavu:dejavu", version.ref = "dejavu" }

detekt-api = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
#detekt-cli = { module = "io.gitlab.arturbosch.detekt:detekt-cli", version.ref = "detekt" }
detekt-test = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt" }
detekt-testUtils = { module = "io.gitlab.arturbosch.detekt:detekt-test-utils", version.ref = "detekt" }
detekt-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detekt-compose" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

diamondedge-logging = { module = "com.diamondedge:logging", version.ref = "diamondedge-logging" }

#essenty-lifecycle = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }
#essenty-backHandler = { module = "com.arkivanov.essenty:back-handler", version.ref = "essenty" }
#essenty-instanceKeeper = { module = "com.arkivanov.essenty:instance-keeper", version.ref = "essenty" }
#essenty-stateKeeper = { module = "com.arkivanov.essenty:state-keeper", version.ref = "essenty" }

#googlePlay-appUpdateKtx = "com.google.android.play:app-update-ktx:2.1.0"
#googlePlay-servicesAnalytics = "com.google.android.gms:play-services-analytics:18.1.1"
#googlePlay-servicesLocation = "com.google.android.gms:play-services-location:21.3.0"
#googlePlay-servicesMaps = "com.google.android.gms:play-services-maps:20.0.0"
#googlePlay-servicesMapsCompose = "com.google.maps.android:maps-compose:8.2.2"
#googlePlay-servicesAds = "com.google.android.gms:play-services-ads:24.4.0"
#googlePlay-servicesAuth = "com.google.android.gms:play-services-auth:20.2.0"
#googlePlay-servicesTagManager = "com.google.android.gms:play-services-tagmanager:18.0.1"
#googlePlay-servicesCast = "com.google.android.gms:play-services-cast-framework:21.1.0"

#facebook-core = { module = "com.facebook.android:facebook-core", version.ref = "facebook" }
#facebook-login = { module = "com.facebook.android:facebook-login", version.ref = "facebook" }

firebaseBom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }

firebaseAnalytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebaseAuth = { group = "com.google.firebase", name = "firebase-auth" }
firebaseAuthKmp = { module = "dev.gitlive:firebase-auth", version = "2.4.0" }
firebaseCrashlytics = { module = "com.google.firebase:firebase-crashlytics" }
#firebaseDatabase = { module = "com.google.firebase:firebase-database" }
#firebaseConfig = { module = "com.google.firebase:firebase-config" }

h2 = { module = "com.h2database:h2", version.ref = "h2" }

hikariCp = { module = "com.zaxxer:HikariCP", version.ref = "hikariCp" }

jetbrains-androidXLifecycleViewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "jetbrains-androidXLifecycle" }
jetbrains-androidXLifecycleViewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "jetbrains-androidXLifecycle" }
jetbrains-androidXNavigation3Runtime = { module = "org.jetbrains.androidx.navigation3:navigation3-runtime", version.ref = "jetbrains-navigation3" }
jetbrains-androidXNavigation3Ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "jetbrains-navigation3" }

jetbrains-composeFoundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "jetBrains-compose" }
jetbrains-composeMaterial3 = { module = "org.jetbrains.compose.material3:material3", version.ref ="jetbrains-composeMaterial3" }
jetbrains-composeRuntime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetBrains-compose" }
jetbrains-composeUi = { module = "org.jetbrains.compose.ui:ui", version.ref = "jetBrains-compose" }
jetbrains-composeMaterialIconsExtended = { module = "org.jetbrains.compose.material:material-icons-extended", version = "1.7.3" }
jetbrains-composeResources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "jetBrains-compose" }
jetbrains-composeMaterial3WindowSizeClass = { module = "org.jetbrains.compose.material3:material3-window-size-class", version.ref = "jetBrains-compose" }
jetbrains-composeUiTooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "jetBrains-compose" }
jetbrains-composeUiToolingPreview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "jetBrains-compose" }
jetbrains-composeBackhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "jetBrains-compose" }

jUnit = { group = "junit", name = "junit", version.ref = "jUnit" }
jUnit5-jupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jUnit5" }
jUnit5-jupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jUnit5" }
#jUnit5-jupiterParams = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jUnit5" }
jUnit5-platformLauncher = { module = "org.junit.platform:junit-platform-launcher", version = "6.1.0" }
#jUnit5-vintageEngine = { module = "org.junit.jupiter:junit-vintage-engine", version.ref = "jUnit5" }

kmpauth-firebase = { module = "io.github.mirzemehdi:kmpauth-firebase", version.ref = "kmpauth" }
kmpauth-firebaseFacebook = { module = "io.github.mirzemehdi:kmpauth-firebase-facebook", version.ref = "kmpauth" }
kmpauth-facebook = { module = "io.github.mirzemehdi:kmpauth-facebook", version.ref = "kmpauth" }
kmpauth-google = { module = "io.github.mirzemehdi:kmpauth-google", version.ref = "kmpauth" }
kmpauth-uihelper = { module = "io.github.mirzemehdi:kmpauth-uihelper", version.ref = "kmpauth" }
kmpnotifier = { group = "io.github.mirzemehdi", name = "kmpnotifier", version.ref = "kmpnotifier" }

#kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertionsCore = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertionsShared = { module = "io.kotest:kotest-assertions-shared", version.ref = "kotest" }
#kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }

kotlin-compilerEmbeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
#kotlin-parcelizeRuntime = { module = "org.jetbrains.kotlin:kotlin-parcelize-runtime", version.ref = "kotlin" }
#kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
#kotlin-testJUnit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

kotlinResult-result = { module = "com.michael-bull.kotlin-result:kotlin-result", version.ref = "kotlinResult" }
#kotlinResult-coroutines = { module = "com.michael-bull.kotlin-result:kotlin-result-coroutines", version.ref = "kotlinResult" }
kotlinRetry = { module = "com.michael-bull.kotlin-retry:kotlin-retry", version.ref = "kotlinRetry" }

kotlinx-coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-collectionsImmutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

ktor-clientAndroid = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
#ktor-clientAuth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }
ktor-clientCio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-clientContentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-clientCore = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-clientDarwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-clientJs = { group = "io.ktor", name = "ktor-client-js", version.ref = "ktor" }
ktor-clientLogging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-clientMock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor" }
ktor-clientOkhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-http = { group = "io.ktor", name = "ktor-http", version.ref = "ktor" }
ktor-io = { group = "io.ktor", name = "ktor-io", version.ref = "ktor" }
ktor-serialization = { group = "io.ktor", name = "ktor-serialization", version.ref = "ktor" }
ktor-serializationKotlinxJson = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-serverCallLogging = { group = "io.ktor", name = "ktor-server-call-logging", version.ref = "ktor" }
ktor-serverContentNegotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serverCore = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor" }
ktor-serverCors = { group = "io.ktor", name = "ktor-server-cors", version.ref = "ktor" }
ktor-serverNetty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-serverStatusPages = { group = "io.ktor", name = "ktor-server-status-pages", version.ref = "ktor" }
ktor-serverTestHost = { group = "io.ktor", name = "ktor-server-test-host", version.ref = "ktor" }
ktor-utils = { group = "io.ktor", name = "ktor-utils", version.ref = "ktor" }

ktorfit-annotations = { group = "de.jensklingenberg.ktorfit", name = "ktorfit-annotations", version.ref = "ktorfit" }
ktorfit-lib = { group = "de.jensklingenberg.ktorfit", name = "ktorfit-lib", version.ref = "ktorfit" }
ktorfit-libLight = { group = "de.jensklingenberg.ktorfit", name = "ktorfit-lib-light", version.ref = "ktorfit" }
ktorfit-ksp = { group = "de.jensklingenberg.ktorfit", name = "ktorfit-ksp", version.ref = "ktorfit" }
ktorfit-convertersResponse = { group = "de.jensklingenberg.ktorfit", name = "ktorfit-converters-response", version.ref = "ktorfit" }

#leakCanary = "com.squareup.leakcanary:leakcanary-android:2.14"

#lottie = "com.airbnb.android:lottie:6.6.7"

metro-gradlePlugin = { module = "dev.zacsweers.metro:dev.zacsweers.metro.gradle.plugin", version.ref = "metro" }
metro-runtime = { module = "dev.zacsweers.metro:runtime", version.ref = "metro" }
metrox-viewmodel = { module = "dev.zacsweers.metro:metrox-viewmodel", version.ref = "metro" }
metrox-viewmodelCompose = { module = "dev.zacsweers.metro:metrox-viewmodel-compose", version.ref = "metro" }
mixpanelAndroid = { module = "com.mixpanel.android:mixpanel-android", version.ref = "mixpanelAndroid" }

#mockk-core = { module = "io.mockk:mockk", version.ref = "mockk" }
#mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
#mockk-dsl = { module = "io.mockk:mockk-dsl", version.ref = "mockk" }

mokkery-core = { module = "dev.mokkery:mokkery-core", version.ref = "mokkery" }

multiplatformSettings-core = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
multiplatformSettings-noargs = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatform-settings" }

okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
#okhttp3-mockWebServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
#okhttp3-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }

#parcelize-darwin-runtime = { module = "com.arkivanov.parcelize.darwin:runtime", version.ref = "parcelize-darwin" }

#retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
#retrofit2-retrofitMock = { module = "com.squareup.retrofit2:retrofit-mock", version.ref = "retrofit" }
#retrofit2-converterGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
#retrofit2-converterKotlinxSerialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
#retrofit2-converterSimpleXml = { module = "com.squareup.retrofit2:converter-simplexml", version.ref = "retrofit" }
#retrofit2-converterMoshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

#revenueCat = "com.revenuecat.purchases:purchases:6.9.8"

#robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }
tensorflowJava = { module = "org.tensorflow:tensorflow-core-platform", version.ref = "tensorflow-java" }

uriKmp = { module = "com.eygraber:uri-kmp", version.ref = "uri-kmp" }
usercentricsUi = { module = "com.usercentrics.sdk:usercentrics-ui", version.ref = "usercentrics" }

#timber = "com.jakewharton.timber:timber:5.0.1"

#Typically used to add declaration for api dependencies, e.g. test-mockk-dsl
[bundles]
#mockk-unit = ["test-mockk-core", "mockk-dsl"]
#mockk-android = ["test-mockk-android", "test-mockk-core", "mockk-dsl"]compose-html-core = { group = "org.jetbrains.compose.html", name = "html-core", version.ref = "compose" }

[plugins]

androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
appDistribution = { id = "com.google.firebase.appdistribution", version.ref = "appDistributionPlugin" }
androidKotlinMultiPlatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }
buildKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }
#compose-screenshotTesting = { id = "com.android.compose.screenshot", version.ref = "compose-screenshotTesting" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlyticsPlugin" }
#dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" } #fine-grained plugin
#dependencyAnalysisBuildHealth = { id = "com.autonomousapps.build-health", version.ref = "dependencyAnalysis" } #settings plugin
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
#gradleDoctor = { id = "com.osacky.doctor", version.ref = "gradleDoctor" }
#graphql = { id = "com.apollographql.apollo", version.ref = "graphql" }
jetBrainsCompose = { id = "org.jetbrains.compose", version.ref = "jetBrains-compose" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
#android-lint = { id = "com.android.lint", version.ref = "androidGradlePlugin" }
#mokkery = { id = "dev.mokkery", version.ref = "mokkery" }
#parcelize-darwin = { id = "com.arkivanov.parcelize.darwin", version.ref = "parcelize-darwin" }
#touchlab-skie = { id = "co.touchlab.skie", version.ref = "skie" }
