package app.purecipes.app.graph

import app.purecipes.feature.analytics.data.repository.AnalyticsDataModule
import app.purecipes.feature.analytics.domain.usecase.ObserveConsentStateUseCase
import app.purecipes.feature.analytics.domain.usecase.RefreshConsentUseCase
import app.purecipes.feature.analytics.domain.usecase.SetAnalyticsUserIdUseCase
import app.purecipes.feature.analytics.domain.usecase.ShowConsentFormUseCase
import app.purecipes.feature.analytics.domain.usecase.TrackEventUseCase
import app.purecipes.feature.auth.data.repository.AuthenticationDataModule
import app.purecipes.feature.auth.domain.usecase.DeleteAccountUseCase
import app.purecipes.feature.auth.domain.usecase.ObserveAuthenticationStateUseCase
import app.purecipes.feature.auth.domain.usecase.RegisterWithEmailUseCase
import app.purecipes.feature.auth.domain.usecase.ResendEmailVerificationUseCase
import app.purecipes.feature.auth.domain.usecase.SendPasswordResetEmailUseCase
import app.purecipes.feature.auth.domain.usecase.SignInWithEmailUseCase
import app.purecipes.feature.auth.domain.usecase.SignInWithExternalProviderUseCase
import app.purecipes.feature.auth.domain.usecase.SignInWithGoogleUseCase
import app.purecipes.feature.auth.domain.usecase.SignOutUseCase
import app.purecipes.feature.favorites.domain.usecase.AddFavoriteRecipeUseCase
import app.purecipes.feature.favorites.domain.usecase.AddRecipeToCookbookUseCase
import app.purecipes.feature.favorites.domain.usecase.CreateCookbookUseCase
import app.purecipes.feature.favorites.domain.usecase.DeleteCookbookUseCase
import app.purecipes.feature.favorites.domain.usecase.GetCookbookCoverImageUrlUseCase
import app.purecipes.feature.favorites.domain.usecase.GetCookbookRecipesPageUseCase
import app.purecipes.feature.favorites.domain.usecase.GetCookbooksPageUseCase
import app.purecipes.feature.favorites.domain.usecase.GetFavoriteRecipesPageUseCase
import app.purecipes.feature.favorites.domain.usecase.GetRecipeCookbooksUseCase
import app.purecipes.feature.favorites.domain.usecase.RemoveFavoriteRecipeUseCase
import app.purecipes.feature.favorites.domain.usecase.RemoveRecipeFromCookbookUseCase
import app.purecipes.feature.measurement.domain.usecase.FilterRecipesForMeasurementPreferencesUseCase
import app.purecipes.feature.measurement.domain.usecase.GetMeasurementPreferencesUseCase
import app.purecipes.feature.measurement.domain.usecase.MarkMeasurementMismatchSeenUseCase
import app.purecipes.feature.measurement.domain.usecase.ObserveMeasurementPreferencesUseCase
import app.purecipes.feature.measurement.domain.usecase.ProcessRecipeDetailsForMeasurementPreferencesUseCase
import app.purecipes.feature.measurement.domain.usecase.ResetMeasurementPreferencesUseCase
import app.purecipes.feature.measurement.domain.usecase.SaveMeasurementPreferencesUseCase
import app.purecipes.feature.newrecipe.domain.usecase.EstimateRecipeNutritionUseCase
import app.purecipes.feature.newrecipe.domain.usecase.GetCreatedRecipesUseCase
import app.purecipes.feature.newrecipe.domain.usecase.SaveCreatedRecipeUseCase
import app.purecipes.feature.recipedetails.domain.usecase.GetRecipeDetailsUseCase
import app.purecipes.feature.search.domain.usecase.GetSearchFiltersUseCase
import app.purecipes.feature.search.domain.usecase.GetUserPantryUseCase
import app.purecipes.feature.search.domain.usecase.SaveSearchFiltersUseCase
import app.purecipes.feature.search.domain.usecase.SearchRecipesUseCase
import app.purecipes.feature.search.domain.usecase.UpdateUserPantryUseCase
import app.purecipes.feature.settings.domain.usecase.ObserveNotificationPreferencesUseCase
import app.purecipes.feature.settings.domain.usecase.SaveNotificationPreferencesUseCase
import app.purecipes.feature.settings.domain.usecase.SendTestNotificationUseCase
import app.purecipes.feature.sharing.domain.usecase.DeliverIncomingLinkUseCase
import app.purecipes.feature.sharing.domain.usecase.ImportCookbookShareUseCase
import app.purecipes.feature.sharing.domain.usecase.ObserveIncomingLinksUseCase
import app.purecipes.feature.sharing.domain.usecase.PublishWebLaunchLinkUseCase
import app.purecipes.feature.sharing.domain.usecase.ShareCookbookUseCase
import app.purecipes.feature.sharing.domain.usecase.ShareRecipeUseCase
import app.purecipes.feature.subscription.domain.usecase.InitializeSubscriptionsUseCase
import app.purecipes.feature.subscription.domain.usecase.ObservePremiumStatusUseCase
import app.purecipes.feature.subscription.domain.usecase.ObserveSubscriptionStateUseCase
import app.purecipes.feature.subscription.domain.usecase.PurchaseSubscriptionUseCase
import app.purecipes.feature.subscription.domain.usecase.RestorePurchasesUseCase
import app.purecipes.feature.subscription.domain.usecase.SyncSubscriptionUserIdUseCase
import app.purecipes.shared.data.config.PurecipesConfig
import app.purecipes.shared.data.network.DataNetworkModule
import dev.zacsweers.metrox.viewmodel.ViewModelGraph

interface CommonAppGraph :
	AnalyticsDataModule,
	AuthenticationDataModule,
	DataNetworkModule,
	ViewModelGraph {

	val purecipesConfig: PurecipesConfig

	val observeConsentStateUseCase: ObserveConsentStateUseCase

	val refreshConsentUseCase: RefreshConsentUseCase

	val setAnalyticsUserIdUseCase: SetAnalyticsUserIdUseCase

	val showConsentFormUseCase: ShowConsentFormUseCase

	val trackEventUseCase: TrackEventUseCase

	val observeAuthenticationStateUseCase: ObserveAuthenticationStateUseCase

	val registerWithEmailUseCase: RegisterWithEmailUseCase

	val resendEmailVerificationUseCase: ResendEmailVerificationUseCase

	val sendPasswordResetEmailUseCase: SendPasswordResetEmailUseCase

	val signInWithEmailUseCase: SignInWithEmailUseCase

	val signInWithExternalProviderUseCase: SignInWithExternalProviderUseCase

	val signInWithGoogleUseCase: SignInWithGoogleUseCase

	val deleteAccountUseCase: DeleteAccountUseCase

	val signOutUseCase: SignOutUseCase

	val addFavoriteRecipeUseCase: AddFavoriteRecipeUseCase

	val getFavoriteRecipesPageUseCase: GetFavoriteRecipesPageUseCase

	val getCookbooksPageUseCase: GetCookbooksPageUseCase

	val createCookbookUseCase: CreateCookbookUseCase

	val deleteCookbookUseCase: DeleteCookbookUseCase

	val getCookbookRecipesPageUseCase: GetCookbookRecipesPageUseCase

	val getCookbookCoverImageUrlUseCase: GetCookbookCoverImageUrlUseCase

	val addRecipeToCookbookUseCase: AddRecipeToCookbookUseCase

	val removeRecipeFromCookbookUseCase: RemoveRecipeFromCookbookUseCase

	val getRecipeCookbooksUseCase: GetRecipeCookbooksUseCase

	val filterRecipesForMeasurementPreferencesUseCase: FilterRecipesForMeasurementPreferencesUseCase

	val getMeasurementPreferencesUseCase: GetMeasurementPreferencesUseCase

	val getCreatedRecipesUseCase: GetCreatedRecipesUseCase

	val getRecipeDetailsUseCase: GetRecipeDetailsUseCase

	val markMeasurementMismatchSeenUseCase: MarkMeasurementMismatchSeenUseCase

	val observeMeasurementPreferencesUseCase: ObserveMeasurementPreferencesUseCase

	val observeNotificationPreferencesUseCase: ObserveNotificationPreferencesUseCase

	val processRecipeDetailsForMeasurementPreferencesUseCase: ProcessRecipeDetailsForMeasurementPreferencesUseCase

	val resetMeasurementPreferencesUseCase: ResetMeasurementPreferencesUseCase

	val removeFavoriteRecipeUseCase: RemoveFavoriteRecipeUseCase

	val saveMeasurementPreferencesUseCase: SaveMeasurementPreferencesUseCase

	val saveNotificationPreferencesUseCase: SaveNotificationPreferencesUseCase

	val sendTestNotificationUseCase: SendTestNotificationUseCase

	val saveCreatedRecipeUseCase: SaveCreatedRecipeUseCase

	val estimateRecipeNutritionUseCase: EstimateRecipeNutritionUseCase

	val getSearchFiltersUseCase: GetSearchFiltersUseCase

	val saveSearchFiltersUseCase: SaveSearchFiltersUseCase

	val getUserPantryUseCase: GetUserPantryUseCase

	val updateUserPantryUseCase: UpdateUserPantryUseCase

	val searchRecipesUseCase: SearchRecipesUseCase

	val deliverIncomingLinkUseCase: DeliverIncomingLinkUseCase

	val observeIncomingLinksUseCase: ObserveIncomingLinksUseCase

	val publishWebLaunchLinkUseCase: PublishWebLaunchLinkUseCase

	val shareRecipeUseCase: ShareRecipeUseCase

	val shareCookbookUseCase: ShareCookbookUseCase

	val importCookbookShareUseCase: ImportCookbookShareUseCase

	val initializeSubscriptionsUseCase: InitializeSubscriptionsUseCase

	val observePremiumStatusUseCase: ObservePremiumStatusUseCase

	val observeSubscriptionStateUseCase: ObserveSubscriptionStateUseCase

	val purchaseSubscriptionUseCase: PurchaseSubscriptionUseCase

	val restorePurchasesUseCase: RestorePurchasesUseCase

	val syncSubscriptionUserIdUseCase: SyncSubscriptionUserIdUseCase
}
